http:
  port: 3000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  instrumento:
    host: localhost
    paths: 
      - '/instrumentos/*'
  aluguel:
    host: localhost
    paths: 
      - '/alugueis/*'

serviceEndpoints:
  instrumento:
    url: 'http://localhost:8080'
  aluguel:
    url: http://localhost:8081'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: aluguel
    apiEndpoints:
      - aluguel
    policies:
      - proxy:
          - action:
              serviceEndpoint: aluguel
  - name: instrumento
    apiEndpoints:
      - instrumento
    policies:
      - proxy:
          - action:
              serviceEndpoint: instrumento 
